version: '3'

networks:
  backend:

services:
  nginx:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    restart: always

  # nginx_cert:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   # build:
  #   #   context: nginx
  #   #   dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   restart: always
  #   networks:
  #     - backend
  #     # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     # - ./nginx/nginx.conf:/nginx/nginx.conf
  #     # - ./nginx:/nginx/ssl_certs



