version: '3'

networks:
  backend:

services:
  nginx:
    image: nginx:latest
    container_name: frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always

  nginx_cert:
    image: nginx:alpine
    container_name: nginx
    # build:
    #   context: nginx
    #   dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/defalt.conf
    restart: always
    networks:
      - backend
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx.conf:/nginx/nginx.conf
      # - ./nginx:/nginx/ssl_certs



