# Generated by Django 5.1.1 on 2024-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_42_user",
            field=models.BooleanField(default=False),
        ),
    ]
