# Generated by Django 4.2.5 on 2024-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0003_user_is_42_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_42_user",
            new_name="is_42",
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(
                default="hello@gmail.com", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="win",
            field=models.IntegerField(default=0),
        ),
    ]
