# Generated by Django 4.2.5 on 2024-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0004_rename_is_42_user_user_is_42_user_bio_user_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.CharField(
                default="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
    ]
