# Generated by Django 4.2.5 on 2024-11-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(default="", max_length=255)),
                ("bio", models.CharField(default="", max_length=1000)),
                ("is_42", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False)),
                ("win", models.IntegerField(default=0)),
            ],
        ),
    ]
