# Generated by Django 4.2.16 on 2024-11-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Match_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='channels_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
