# Generated by Django 4.2.5 on 2025-01-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_user_is_online_user_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
