# Generated by Django 4.2.5 on 2025-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0003_alter_user_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
