# Generated by Django 4.2.5 on 2025-02-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='Hello Everyone, Nice to meet you guy!', max_length=1000),
        ),
    ]
