FROM ubuntu:22.04

WORKDIR /usr/src/app

# This copies all files including start.sh to /app in the container
RUN mkdir User_manage

COPY ./User_manage ./User_manage
COPY ./data/start.sh . 

# Make sure start.sh is executable
RUN chmod +x /usr/src/app/start.sh

# Install dependencies (example: Python and others)
RUN apt-get update && apt-get install -y --no-install-recommends python3.10 python3-pip curl libpq-dev vim

# Install Python dependencies (assuming you have a requirements.txt)
COPY ./data/requirements.txt .

RUN pip install -r requirements.txt

# Expose the port Django will run on
EXPOSE 8001

# Start the app with start.sh
CMD ["sh", "/usr/src/app/start.sh"]
