FROM ubuntu:22.04

WORKDIR /usr/src/app

RUN mkdir User_manage

COPY ./User_manage ./User_manage
COPY ./data/start.sh .
COPY ./data/requirements.txt .
COPY ./.env ./
COPY ./wait-for-postgres.sh ./

RUN chmod +x /usr/src/app/start.sh

RUN apt-get update && apt-get install -y --no-install-recommends python3.10 python3-pip curl libpq-dev vim postgresql-client
    
RUN pip install -r requirements.txt

RUN chmod +x ./wait-for-postgres.sh
ENTRYPOINT ["./wait-for-postgres.sh"]

EXPOSE 8001

CMD ["sh", "/usr/src/app/start.sh"]
