# Generated by Django 4.2.5 on 2024-12-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(null=True),
        ),
    ]
