# Generated by Django 4.2.16 on 2024-11-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('online_status', models.BooleanField(default=False)),
                ('current_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QueueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=100)),
                ('queue_size', models.IntegerField()),
                ('queue_status', models.BooleanField(default=False)),
                ('queue_players', models.ManyToManyField(related_name='queue_players', to='Match_manager.playersession')),
            ],
        ),
        migrations.AddField(
            model_name='playersession',
            name='curent_queue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Match_manager.queuesession'),
        ),
    ]
