# Generated by Django 4.2.5 on 2024-11-24 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.FileField(blank=True, null=True, upload_to="upload/"),
                ),
                (
                    "bio",
                    models.CharField(
                        default="Hello Everyone, Nice to meet you guy!", max_length=1000
                    ),
                ),
                ("win", models.IntegerField(default=0)),
                ("loss", models.IntegerField(default=0)),
                ("draw", models.IntegerField(default=0)),
                ("total_match", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
