# Generated by Django 4.2.5 on 2024-11-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
    ]
