# Generated by Django 4.2.5 on 2024-11-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0002_remove_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="loss",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="total_match",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="win",
        ),
    ]
